
name: Pack and Push Solution
run-name: Pack and Push Solution

on:
  push:
    branches:    
      - main

jobs:
  Pack-And-Push:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0 # This is nescessary so it does not conflict with git-version

      - name: Run cake step
        uses: cake-build/cake-action@v3
        with:
          script-path: build.cake
          target: NugetPackAndPush
          NuGetApiKey: ${{ secrets.PUBLIC_NUGET_APIKEY }}
          NuGetSource: ${{ vars.PUBLIC_NUGET_SOURCE }}
          SonarOrg: ${{ vars.SONARORG }}
          SonarToken: ${{ secrets.SONARTOKEN }}
          SonarHostUrl: ${{ vars.SONARHOST }}
          SonarProjectKey: ${{ secrets.SONAR_PROJ_KEY }}
          SonarProjectName: ${{ vars.SONAR_PROJ_NAME }}

      - name: Publish Artifacts
        uses: actions/upload-artifact@v7
        with:
          name: Artifacts
          path: ./artifacts/